language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django==1.7" DB=mysql
  - DJANGO="Django==1.8" DB=mysql
install:
  - pip install -U $DJANGO
  - pip install -U -r pipreq.txt --exists-action=w
script:
  - python manage.py test
